name: ela
channels:
  - conda-forge
dependencies:
  - rasterio
  - cartopy
  - geopandas
  - pandas
  - nltk
  - scikit-learn
  - scikit-image
  - matplotlib
  - vtk
  - pyqt
  - mayavi
  - pyvista
  - pip:
    - "--editable=git+https://github.com/DennisHgj/pyela@master"
