name: ela
channels:
  - conda-forge
dependencies:
  - rasterio
  - cartopy
  - geopandas
  - pandas
  - nltk
  - scikit-learn
  - scikit-image
  - matplotlib
  - vtk
  - pyqt5
  - mayavi
  - pyvista
  - git+git://github.com/DennisHgj/pyela@master
